### ISSUE TITLE
Update Help page to be same as iOS

### ISSUE THREAD

**Issue by PaulDGillis** [TigerHacks/app-android#36]
Just need to fix icons.

**Comment by AJM-1** [comment]
add devpost link
switch link sections so Tigerhacks focused links are on top

**Comment by AJM-1** [comment]
Paul added Social links and changed the title

**Comment by PaulDGillis** [comment]
Updated with icons, not adding Facebook or Instagram's since Instragram is really picky on the guidelines to use their icon.
